font_size 14
font_family JetBrains Mono
cursor_trail 50
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_windown_close 0
enabled_layouts splits

map alt+c send_text all \x0c
map ctrl+n launch --location=split --cwd=current
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

# BEGIN_KITTY_THEME
# Selenized White
include themono.conf
# END_KITTY_THEME
